apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: arpjoker/api-kuber 
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: api-service 
spec:
  selector:
    app.kubernetes.io/name: api
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8000