apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: arpjoker/api-kuber
        livenessProbe:
          httpGet:
            path: /status
            port: 8000
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service 
spec:
  type: NodePort
  selector:
    app: api
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30100
