apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: {{ .Values.ser.name }}
        image: arpjoker/api-kuber
        livenessProbe:
          httpGet:
            path: /status
            port: 8000 
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ser.name }}
spec:
  type: NodePort
  selector:
    app: api
  ports: 
    - protocol: {{ .Values.ser.spec.protocol }} 
      port: {{ .Values.ser.spec.port }} 
      targetPort: 8000
      nodePort: {{ .Values.ser.nodePort }}
